In [3]:


# linear algebra

# helps to find the linear transformation between two variables


# numpy - linear algebra library for Python. made of c++


# the first image of a black hole was clicked using NumPy

In [11]:
import numpy as np

# vector - 1 D array
# Matrices - 2 D array

vector = [11,24,56,78]
n1=np.array(vector)
print(n1)



matrix = ([1,2,3],[-8,-9,0],[-11,0,1])
n2=np.array(matrix)
print(n2)

[11 24 56 78]
[[  1   2   3]
 [ -8  -9   0]
 [-11   0   1]]


In [13]:
# checking the type


type(n1)
type(n2)

numpy.ndarray

In [58]:
# built-in functions

# arange

t = np.arange(60,160,5)
t

a = np.arange(10,500,63)
a


# zeros


# one dimensions
z = np.zeros(3)
print(z)


# two dimensions
z2=np.zeros((3,4))
print(z2)

# without decimal points

z3 = np.zeros((3,3), dtype=int)
print(z3)



# ones

one=np.ones((3,3), dtype = int)
print(one)






# linspace

# returns evenly spaced number over an interval

# np.linspace(start,stop,num)

x=np.linspace(0,34)

# np.linspace(0,34) would generate an array of 34 evenly spaced numbers between 0 and 34, inclusive.

# In linspace, the difference between two consecutive numbers is always the same
# in below example: 0.69387755 - 1.3877551 = 0.69387755
# 1.3877551 - 2.08163265 = 0.69387755
# 2.08163265 - 2.7755102 = 0.69387755

y=np.arange(0,30)

# np.arange(0,10) would generate an array containing values from 0 up to, but not including, 10 with a step size of 1.


print(x)
print(y)


# 10 values between 0 and 10 that should be evenly split

test= np.linspace(0,10,10)
print(test)




# eye


# like identity matrix

print(np.eye(4))



# random

# random.rand() generates in a uniform distribution

print(np.random.rand(10))

n = np.random.rand(5,5)
print(n)

n3 = np.random.rand(3,3,4)
print("\n 3d array \n",n3)







# random.randn() -> normal distribution


norm = np.random.randn(3)
print(norm)


# random.randint(low,high,count) -> discrete uniform distribution

print(np.random.randint(10,104,8))

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[ 0.          0.69387755  1.3877551   2.08163265  2.7755102   3.46938776
  4.16326531  4.85714286  5.55102041  6.24489796  6.93877551  7.63265306
  8.32653061  9.02040816  9.71428571 10.40816327 11.10204082 11.79591837
 12.48979592 13.18367347 13.87755102 14.57142857 15.26530612 15.95918367
 16.65306122 17.34693878 18.04081633 18.73469388 19.42857143 20.12244898
 20.81632653 21.51020408 22.20408163 22.89795918 23.59183673 24.28571429
 24.97959184 25.67346939 26.36734694 27.06122449 27.75510204 28.44897959
 29.14285714 29.83673469 30.53061224 31.2244898  31.91836735 32.6122449
 33.30612245 34.        ]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[

In [90]:


# array attributes and methods




arr = np.arange(10,25)
print(arr)

arr1 = np.random.randint(10,25,30)
print(arr1)





# reshape


arr_reshape = arr.reshape(3,5)
print("arr reshape \n",arr_reshape)

arr1_reshape = arr1.reshape(6,5)
print("arr1 reshape \n",arr1_reshape)

arr2_reshape = arr1.reshape(30,1)
print("arr2 reshape \n",arr2_reshape)


# argmin and argmax

# argmin -> gives the index of the minimum values
# argmax -> gives the index of the maximum value


print(np.argmin(arr))
print(np.argmax(arr))


# or 

arr.argmin()
arr.argmax()




# shape -> to check the dimensions of the array

n1 = np.random.randn(3,6)
n1.reshape(9,2)
x = n1.shape
print("shape is \n",x)
print("n1 is \n",n1)


n1.dtype

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[18 11 23 16 22 12 14 18 18 19 11 17 10 18 16 14 12 17 21 20 12 15 13 19
 23 21 23 10 17 12]
arr reshape 
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
arr1 reshape 
 [[18 11 23 16 22]
 [12 14 18 18 19]
 [11 17 10 18 16]
 [14 12 17 21 20]
 [12 15 13 19 23]
 [21 23 10 17 12]]
arr2 reshape 
 [[18]
 [11]
 [23]
 [16]
 [22]
 [12]
 [14]
 [18]
 [18]
 [19]
 [11]
 [17]
 [10]
 [18]
 [16]
 [14]
 [12]
 [17]
 [21]
 [20]
 [12]
 [15]
 [13]
 [19]
 [23]
 [21]
 [23]
 [10]
 [17]
 [12]]
0
14
shape is 
 (3, 6)
n1 is 
 [[-0.55251146 -0.83147608  1.03009145 -0.48032899 -0.52224644  1.45634415]
 [-0.04985395 -1.06150187  0.51562024  0.74318093 -0.77944209 -0.16472922]
 [ 0.49306242 -0.31396498  0.07554375  1.23880962 -1.39741112 -0.11525674]]


dtype('float64')

In [106]:
# numpy indexing and selection





x = np.random.randint(0,60,30)
print(x)
print(x[13:17])
print(x[:17])




# grabbing an array  -> 

arr = np.arange(10,25)
print(arr)
slice_arr = arr[3:8]
print("slice of an array \n",slice_arr)
slice_arr[:] = 1011
print("if we do that, it will get reflected in actual array itself \n")
print("slice of an array \n",slice_arr)

print("actual array \n",arr)



# hence whenever we perform any analysis, we should make a copy

arr = np.arange(1,60)
print("\n array",arr)
copy_of_arr = arr.copy()
print("copy of array \n",copy_of_arr)
copy_of_arr[:]=1056
print("copy \n",copy_of_arr)
print("actual array \n",arr)



[23  7 51 32  1  9 20 53 59 58  6 53 50 35 25 50 59 36 42 30  0  8 11  8
 19 27 30 22 13 14]
[35 25 50 59]
[23  7 51 32  1  9 20 53 59 58  6 53 50 35 25 50 59]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
slice of an array 
 [13 14 15 16 17]
if we do that, it will get reflected in actual array itself 

slice of an array 
 [1011 1011 1011 1011 1011]
actual array 
 [  10   11   12 1011 1011 1011 1011 1011   18   19   20   21   22   23
   24]

 array [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59]
copy of array 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59]
copy 
 [1056 1056 1056 1056 1056 1056 1056 1056 1056 1056 1056 1056 1056 1056
 1056 1056 1056 1056 1056 1056 1056 1056 1056 1056 1056 1056 1056 1056
 1056 1056 1056 105

In [135]:




# 2 D array 




# Indexing on 2D array

arr_2d = np.array([[1,3,5],[55,6,7],[11,3,4]])
arr_2d

print(arr_2d)

# accessing first index


print(arr_2d[1])

# accessing second index

print(arr_2d[2])

print(arr_2d[2][1])


# accessing the specific element

print("\n need to grab the 3,5 and 6,7 \n",arr_2d)

# first lets exclude the elements which we don't need

print(arr_2d[:2])

# now lets take 3,5 and 6,7

print(arr_2d[:2,1:])

[[ 1  3  5]
 [55  6  7]
 [11  3  4]]
[55  6  7]
[11  3  4]
3

 need to grab the 3,5 and 6,7 
 [[ 1  3  5]
 [55  6  7]
 [11  3  4]]
[[ 1  3  5]
 [55  6  7]]
[[3 5]
 [6 7]]


In [164]:
arr_2d = np.array([
    [1,3,5],
    [55,6,7],
    [11,3,4]])

print(arr_2d)

# arr_2d[[0, 2], [0, 2]]
# arr_2d[row-indices[[coloumn-indices]
# arr_2d[[0,2],[0,2]] -> row(0,0) and column(2,2)

arr_2d[[0,2],[0,2]]

[[ 1  3  5]
 [55  6  7]
 [11  3  4]]


array([1, 4])

In [185]:
arr_2d = np.array([
    [1,3,5],
    [55,6,7],
    [11,3,4]])

# step 1: exclude the element

# step 2: grab / slice from the rest

# element we wanted to take - 1,3 and 55,6

# arr_2d[exclude-row,min coloumn:max column]

print(arr_2d[0:2,:2])

[[ 1  3]
 [55  6]]


In [189]:
arr_2d = np.array([
    [1,3,5],
    [55,6,7],
    [11,3,4]])

# element we wanted to take - 6,7 and 3,4

# step 1 - exclude element which we don't need

print(arr_2d[1:,1:])


[[6 7]
 [3 4]]


In [194]:
arr_2d = np.array([
    [1,3,5],
    [55,6,7],
    [11,3,4]])


# elements we need -> 3,5 and 3,4

# we need 0 and 2 rows starting coloumns 1 and 2

# hence
print(arr_2d[[0,2],1:])

# elements we need -> 3,5 and 6,7
print(arr_2d[[0,1],1:])

[[3 5]
 [3 4]]
[[3 5]
 [6 7]]


In [219]:
arr_2d = np.array([
    [1,3,5],
    [55,6,7],
    [11,3,4]])

arr_2d

# element we want 1,11 and 5 and 4
print(arr_2d[[0, 2], [0, 2]])



[1 4]


In [227]:


ar = np.zeros((5,5))
ar

ar_len = ar.shape[1]
ar_len

for i in range(ar_len):
    print(ar[i])

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


In [228]:


ar = np.zeros((5,5))
ar

ar_len = ar.shape[1]
ar_len

for i in range(ar_len):
    ar[i] = i


print(ar)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [231]:

# fancy indexing

ar = np.zeros((5,5))
ar

ar_len = ar.shape[1]
ar_len

for i in range(ar_len):
    ar[i] = i


print(ar)


# fancy indexing, grabbing the rows we want

ar[[0,3,4]]


[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


array([[0., 0., 0., 0., 0.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [249]:
# selection


ar = np.arange(1,70,5)
print(ar)
print(ar>15)

bool_arr = ar>15


# getting all the true values

print(ar[bool_arr])

print(ar[ar>15])

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66]
[False False False  True  True  True  True  True  True  True  True  True
  True  True]
[16 21 26 31 36 41 46 51 56 61 66]
[16 21 26 31 36 41 46 51 56 61 66]


In [254]:
# operation

print(ar) 

print(ar + ar)

print(ar - ar)

print(ar / ar)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66]
[  2  12  22  32  42  52  62  72  82  92 102 112 122 132]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [259]:
# Universal array functions

print(ar)

print(np.sqrt(ar))

print(np.exp(ar))

print(np.max(ar))

print(np.log(ar))

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66]
[1.         2.44948974 3.31662479 4.         4.58257569 5.09901951
 5.56776436 6.         6.40312424 6.78232998 7.14142843 7.48331477
 7.81024968 8.1240384 ]
[2.71828183e+00 4.03428793e+02 5.98741417e+04 8.88611052e+06
 1.31881573e+09 1.95729609e+11 2.90488497e+13 4.31123155e+15
 6.39843494e+17 9.49611942e+19 1.40934908e+22 2.09165950e+24
 3.10429794e+26 4.60718663e+28]
66
[0.         1.79175947 2.39789527 2.77258872 3.04452244 3.25809654
 3.4339872  3.58351894 3.71357207 3.8286414  3.93182563 4.02535169
 4.11087386 4.18965474]
